apikey: ""
registry: 577926974532.dkr.ecr.us-east-1.amazonaws.com
debug: true
namespace: "zestfulset-controller-system"

cloud:
  name: "Amazon"
  dynamicdataEndpoint:
    ipv4: "http://169.254.169.254/latest/dynamic"
  metadataEndpoint:
    ipv4: "http://169.254.169.254/latest/meta-data"
    ivp6: "http://[fd00:ec2::254]/latest/meta-data"

storageClass:
  create: true
  type: "gp2"
  csi.storage.k8s.io/fstype: "btrfs"

collector:
  prometheusSideCar:
    appName: zesty-prometheus-exporter
    logLevel: "DEBUG"
    image:
      name: prometheus
      tag: latest
      pullPolicy: Always
    port: 80
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
  appName: zesty-collector
  logLevel: "DEBUG"
  image:
    name: collector
    tag: latest
    pullPolicy: Always
  livenessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 15
    periodSeconds: 20
  readinessProbe:
    tcpSocket:
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 10
  resources:
    limits:
      cpu: "1"
    requests:
      cpu: "0.5"
  apikeyPath: "/zesty/collector/.apikey"
  installBtrfsOnNodes: true
  initContainers:
    detector:
      image:
        name: detector
