# Prod values of the chart, it will be merged with env specific values into values.yaml
prefixName: ""
serviceAccount:
  create: true
  name: "zesty-serviceaccount"
registry: "672188301118.dkr.ecr.eu-west-1.amazonaws.com"
imagePullSecrets: []
provisioner:
  image:
    name: zd/k8s/controller
    tag: 1.1.51
agent:
  baseUrl: https://sedz7kc6sc.execute-api.eu-west-1.amazonaws.com/k8s
  apiKey: ""
  collector:
    image:
      name: zd/k8s/collector
      tag: 1.0.36
  sidecar:
    image:
      name: zd/k8s/sidecar
      tag: 1.3.14
  prometheusExporter:
    image:
      name: zd/k8s/prometheus-exporter
      tag: 1.0.0
    port: ""
