# Prod values of the chart, it will be merged with env specific values into values.yaml
prefixName: ""
serviceAccount:
  create: true
  name: "zesty-serviceaccount"
registry: "672188301118.dkr.ecr.eu-west-1.amazonaws.com"
imagePullSecrets: []
provisioner:
  image:
    name: zd/k8s/controller
    tag: 1.1.60
agent:
  secret:
    name: zesty-disk-agent-cred
  baseUrl: https://sedz7kc6sc.execute-api.eu-west-1.amazonaws.com/k8s
  apiKey: "" # if you put the value here, the secret won't be used.
  collector:
    image:
      name: zd/k8s/collector
      tag: 1.0.42
  sidecar:
    image:
      name: zd/k8s/sidecar
      tag: 1.3.19
  prometheusExporter:
    image:
      name: zd/k8s/prometheus-exporter
      tag: 1.0.0
    port: ""
nodeSelector: {}
tolerations: {}

