# RND values of the chart, it will be merged with env specific values into values.yaml
prefixName: ""
serviceAccount:
  create: true
  name: "zesty-serviceaccount"
registry: "577926974532.dkr.ecr.us-west-2.amazonaws.com"
imagePullSecrets: []
provisioner:
  image:
    name: zd/k8s/controller
    tag: 1.1.46
agent:
  baseUrl: https://papze4fl14.execute-api.us-west-2.amazonaws.com/k8s
  apiKey: ""
  collector:
    image:
      name: zd/k8s/collector
      tag: 1.0.34
  sidecar:
    image:
      name: zd/k8s/sidecar
      tag: 1.3.11
