apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.controller.appName }}-informer-configmap
data:
  CLOUD_PROVIDER: {{ .Values.cloud.name }}
  AWS_METADATA_VERSION: "2020-10-27"
  AZURE_METADATA_VERSION: "2020-09-01"
  API_KEY: {{ .Values.apikey }}
  CLOUD_NAME: {{ .Values.cloud.name }}
  METADATA_URL: {{ .Values.cloud.metadataEndpoint.ipv4 }}
  DYNAMIC_DATA_URL: {{ .Values.cloud.dynamicdataEndpoint.ipv4 }}
  TAG_VOLUME_ENDPOINT: {{ .Values.controller.informer.appConfig.tagVolumeEndpointURL }}
  DELETE_VOLUMES_ENDPOINT: {{ .Values.controller.informer.appConfig.deleteVolumesEndpointURL }}
  {{- if .Values.debug }}
  DEBUG: "true"
  {{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.collector.appName }}-apikey
data:
  apikey: {{ .Values.apikey }}

---

apiVersion: v1
kind: Secret
stringData:
  apiKey: {{ .Values.apikey }}
metadata:
  name: {{ .Values.controller.appName }}-secret
type: Opaque
