apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.collector.appName }}-configmap
  namespace: {{ .Values.namespace }}
data:
  CLOUD_PROVIDER: {{ .Values.cloud.name }}
  AWS_METADATA_VERSION: "2020-10-27"
  AZURE_METADATA_VERSION: "2020-09-01"
  API_KEY: {{ .Values.apikey }}
  CLOUD_NAME: {{ .Values.cloud.name }}
  METADATA_URL: {{ .Values.cloud.metadataEndpoint.ipv4 }}
  DYNAMIC_DATA_URL: {{ .Values.cloud.dynamicdataEndpoint.ipv4 }}
  {{- if .Values.debug }}
  DEBUG: "true"
  {{- end}}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.collector.appName }}-apikey
  namespace: {{ .Values.namespace }}
data:
  apikey: {{ .Values.apikey }}
