apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-controller
  labels:
    app: {{ .Values.controller.appName }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.controller.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.appName }}
    spec:
      serviceAccountName: {{ .Values.controller.appName }}-serviceaccount
      containers:
      - name: {{ .Values.controller.appName }}-{{ .Values.controller.informer.appName }}
        envFrom:
        - configMapRef:
            name: {{ .Values.controller.appName }}-configmap
        {{- with .Values.controller.informer.image }}
        image: {{ $.Values.registry }}/{{ .name }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
      - name: {{ .Values.controller.appName }}-{{ .Values.controller.manager.appName }}
        envFrom:
        - configMapRef:
            name: {{ .Values.controller.appName }}-configmap
        {{- with .Values.controller.manager.image }}
        image: {{ $.Values.registry }}/{{ .name }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
