apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "agent.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "agent.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "agent.name" . }}
    spec:
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 6 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostPID: true
      containers:
        - name: agent
          image: {{ include "collector.image" . }}:{{ .Values.agent.collector.image.tag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: host-path-mnt
              mountPath: /mnt
            - name: host-path-dev
              mountPath: /dev
            - name: shared
              mountPath: /host
          securityContext:
            privileged: true
          env:
            - name: ZESTY_BASE_URL
              value: {{ .Values.agent.baseUrl | quote }}
          {{- if ne .Values.agent.apiKey ""}}
            - name: ZESTY_API_KEY
              value: {{ .Values.agent.apiKey | quote }}
          {{- end }}
          {{- if eq .Values.agent.apiKey "" }}
          envFrom:
          - secretRef:
                name: {{ .Values.agent.secret.name | quote }}
           {{- end }}
        - name: sidecar
          image: {{ include "sidecar.image" . }}:{{ .Values.agent.sidecar.image.tag }}
          imagePullPolicy: Always
        {{- if .Values.agent.prometheusExporter.port }}
        - name: prometheus-exporter
          image: {{ include "prometheusExporter.image" . }}:{{ .Values.agent.prometheusExporter.image.tag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: shared
              mountPath: /host
          env:
            - name: PROMETHEUS_EXPORTER_PORT
              value: {{ .Values.agent.prometheusExporter.port | quote}}
        {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: host-path-mnt
          hostPath:
            path: /mnt
        - name: host-path-dev
          hostPath:
            path: /dev
        - name: shared
          emptyDir: {}
