{{- if .Values.storageClass.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zesty-storageclass
  labels:
    app: zesty-disk
provisioner: kubernetes.io/aws-ebs
parameters:
  type: {{ default "gp2" .Values.storageClass.type }}
  fsType: {{ default "btrfs" .Values.storageClass.fsType }}
  {{ if .Values.storageClass.availabilityZone }}
  zone: {{ .Values.storageClass.availabilityZone }}
  {{ end }}
{{- end }}
